baseURL = "https://dominatedbycline.github.io/"
languageCode = "en-us"
title = "Dominated by Cline"
theme = "archie"
copyright = "© Maria Lu"

# Code Highlighting
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# Pagination
paginate = 5

[params]
  mode = "auto"  # color-mode: light, dark, toggle, or auto
  useCDN = false  # serve fonts/icons locally
  subtitle = "AI-assisted development log"
  
  # Math support (optional)
  mathjax = false
  katex = false

# Social links
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/marialu1"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "All Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/tags/project"
  weight = 3

[[menu.main]]
  name = "Mystery Crime Party"
  url = "/tags/mystery-crime-party"
  weight = 4

[[menu.main]]
  name = "AI Tools"
  url = "/tags/ai"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 6
