baseURL = "https://dominatedbycline.github.io/"
languageCode = "en-us"
title = "Dominated by Cline"
theme = "archie"
copyright = "© Maria Lu"
enableRobotsTXT = true

# Code Highlighting
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# Pagination
[pagination]
  pagerSize = 5

# Allow raw HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mode = "auto"  # color-mode: light, dark, toggle, or auto
  useCDN = false  # serve fonts/icons locally
  subtitle = "Building ridiculous projects with AI assistance (and documenting every weird decision)"
  customCSS = ["css/custom.css", "css/code-copy.css"]

  # Math support (optional)
  mathjax = false
  katex = false

  # RSS
  rssLimit = 20

  # Author info for SEO
  author = "Maria Lu"
  description = "Building ridiculous projects with AI assistance"

  # Custom JS
  customJS = ["js/code-copy.js"]

  # Analytics - Choose one:
  # Option 1: Plausible (privacy-friendly, recommended)
  # Sign up at https://plausible.io/ and add your domain
  # Then uncomment and add this to customJS:
  # customJS = ["js/code-copy.js", "https://plausible.io/js/script.js"]
  # And add: data-domain="your-domain.com" attribute
  #
  # Option 2: Google Analytics
  # Uncomment the line below and add your GA4 ID:
  # googleAnalytics = "G-XXXXXXXXXX"

  # Giscus comments (GitHub Discussions)
  [params.giscus]
    repo = "dominatedbycline/dominatedbycline.github.io"
    repoId = "R_kgDOQBj2TA"
    category = "Announcements"
    categoryId = "DIC_kwDOQBj2TM4Cw0_X"
    theme = "preferred_color_scheme"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/marialu1"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Guides"
  url = "/guides"
  weight = 2

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 3

[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 4

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 6
