baseURL = "https://dominatedbycline.github.io/"
languageCode = "en-us"
title = "Dominated by Cline"
theme = "archie"
copyright = "© Maria Lu"

# Code Highlighting
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# Pagination
[pagination]
  pagerSize = 5

[params]
  mode = "auto"  # color-mode: light, dark, toggle, or auto
  useCDN = false  # serve fonts/icons locally
  subtitle = "Building ridiculous projects with AI assistance (and documenting every weird decision)"
  customCSS = ["css/custom.css"]
  
  # Math support (optional)
  mathjax = false
  katex = false

# Social links
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/marialu1"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4
