baseURL = "https://dominatedbycline.github.io/"
languageCode = "en-us"
title = "Dominated by Cline"
theme = "archie"
copyright = "© Maria Lu"
enableRobotsTXT = true

# Code Highlighting
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# Pagination
[pagination]
  pagerSize = 5

# Allow raw HTML in markdown
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mode = "auto"  # color-mode: light, dark, toggle, or auto
  useCDN = false  # serve fonts/icons locally
  subtitle = "Building ridiculous projects with AI assistance (and documenting every weird decision)"
  customCSS = ["css/custom.css", "css/code-copy.css", "css/reading-progress.css", "css/back-to-top.css", "css/print.css", "css/dark-mode-toggle.css"]

  # Math support (optional)
  mathjax = false
  katex = false

  # RSS
  rssLimit = 20

  # Author info for SEO
  author = "Maria Lu"
  description = "Building ridiculous projects with AI assistance"

  # Custom JS
  customJS = ["js/code-copy.js", "js/reading-progress.js", "js/back-to-top.js", "js/keyboard-shortcuts.js", "js/dark-mode-toggle.js", "js/image-lightbox.js"]

  # Analytics - GoatCounter (privacy-friendly, free, open source)
  # Sign up at https://goatcounter.com (FREE!)
  # Get your username and add it below:
  goatCounter = "dominatedbycline"  # Your GoatCounter username
  # Dashboard: https://dominatedbycline.goatcounter.com

  # Giscus comments (GitHub Discussions)
  [params.giscus]
    repo = "dominatedbycline/dominatedbycline.github.io"
    repoId = "R_kgDOQBj2TA"
    category = "Announcements"
    categoryId = "DIC_kwDOQBj2TM4Cw0_X"
    theme = "preferred_color_scheme"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/marialu1"

# Menu
[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Guides"
  url = "/guides"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4
